In [ ]:
import torch
seed = 1234
device = "cuda" if torch.cuda.is_available else "cpu"
torch.manual_seed(seed)
tensor_a = torch.rand(2,3)
tensor_a_on_gpu=tensor_a.to(device)
tensor_b = torch.rand(2,3)
tensor_b_on_gpu=tensor_b.to(device)
print(tensor_a_on_gpu , tensor_b_on_gpu)


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


In [ ]:
torch_mm = torch.mm(tensor_a_on_gpu,tensor_b_on_gpu.T)
print(torch_mm)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


In [ ]:
torch_mm.max() , torch_mm.min()

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [ ]:
torch_mm.argmin() , torch_mm.argmax()

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))

In [ ]:
seed = 7
torch.manual_seed(seed)
tensor_x = torch.rand(size=(1,1,1,10))
tensor_y = torch.squeeze(tensor_x)
tensor_z = torch.squeeze(tensor_y)
tensor_xx = torch.squeeze(tensor_z)
print(tensor_xx)


tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
