In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [ ]:
scalar.ndim

0

In [ ]:
# vector
vector = torch.tensor([1,2,4,5,6,7])
vector
print(vector.shape)
print(vector.ndim)

torch.Size([6])
1


In [ ]:
# matrix
matrix = torch.tensor([[1,2,3,4],[3,4,5,6],[2,2,2,2]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[1, 2, 3, 4],
        [3, 4, 5, 6],
        [2, 2, 2, 2]])
2
torch.Size([3, 4])


In [ ]:
# tensor
tensor = torch.tensor([[[1,1],[2,2],[9,3],[4,4]],
                       [[3,3],[4,4],[5,5],[5,5]]
                      ])
print(tensor.shape)
print(tensor.ndim)
print(tensor[0,2,0])

torch.Size([2, 4, 2])
3
tensor(9)


### random tensor

In [ ]:
tensor = torch.rand(2,2,3)
tensor

tensor([[[0.0703, 0.0564, 0.0181],
         [0.2827, 0.3373, 0.2033]],

        [[0.1501, 0.2189, 0.2562],
         [0.7795, 0.2606, 0.2085]]])

In [ ]:
zeros = torch.zeros(size=(4,2,2))
zeros

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [ ]:
# torch range
range = torch.arange(start=1, end=100 , step=7)
range

tensor([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99])

tensor datatypes :
1. 32 float point
2. 16 float point
commonly used in pytorch
we should know this coz we may get errors such as
1. tensor not right datatype
2. tensor not rght shape
3. tensor not on right device like 1 may run in cpu and other in gpu

In [ ]:
tensor_datatypes = torch.rand(size=(2,3,4), dtype=torch.float16 ,
                              device=None ,
                              requires_grad= False )
print(tensor_datatypes)
tensor_datatypes.dtype

tensor([[[0.6567, 0.2778, 0.7520, 0.5283],
         [0.3940, 0.8867, 0.8281, 0.7212],
         [0.1191, 0.4326, 0.8828, 0.1860]],

        [[0.1479, 0.8179, 0.9126, 0.9966],
         [0.2837, 0.3657, 0.5996, 0.5000],
         [0.9551, 0.5049, 0.5879, 0.0371]]], dtype=torch.float16)


torch.float16

In [ ]:
tensor_float32 = torch.rand(size=(1,3,4) , dtype=torch.float32)
tensor_float32.dtype

torch.float32

In [ ]:
tensor_datatypes.shape


torch.Size([2, 3, 4])

In [ ]:
# matrix multiplication
%%time
tensor1 = torch.tensor([[1,2],[2,3]])
tensor2 = torch.tensor([[1,2],[2,3]])
torch.matmul(tensor1,tensor2)

CPU times: user 1.84 ms, sys: 0 ns, total: 1.84 ms
Wall time: 2.74 ms


tensor([[ 5,  8],
        [ 8, 13]])

In [ ]:
torch.mm(torch.rand(size=(7,3)),torch.rand(size=(3,8))).shape

torch.Size([7, 8])

In [ ]:
tensor1 = torch.tensor([[1,2],
                        [2,3],
                        [3,4]])

tensor2 = torch.tensor([[4,5],
                        [5,6],
                        [6,7]])
torch.mm(tensor1,tensor2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# to solve the inner dimension error or tensor error we can change the
# shape by transpose but ** note:- data wont be affected it will be same **

torch.mm(tensor1 , tensor2.T)


tensor([[14, 17, 20],
        [23, 28, 33],
        [32, 39, 46]])

In [ ]:
tensor = torch.arange(1,100,8)
tensor

tensor([ 1,  9, 17, 25, 33, 41, 49, 57, 65, 73, 81, 89, 97])

In [ ]:
tensor.min()  ,   torch.min(tensor)

(tensor(1), tensor(1))

In [ ]:
tensor.max()   ,  torch.max(tensor)

(tensor(97), tensor(97))

In [ ]:
tensor.mean()  ,   torch.mean(tensor)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
# here we finally get data type error and it says to either be float or
# complex not long so now we convert data type

x = tensor.type(torch.float32)

x.mean()  ,   torch.mean(x)


(tensor(49.), tensor(49.))

In [ ]:
x.dtype , tensor.dtype


(torch.float32, torch.int64)

In [ ]:
torch.sum(tensor)

tensor(637)

In [ ]:
torch.argmin(tensor)  , torch.argmax(tensor)

(tensor(0), tensor(12))

In [ ]:
y = torch.rand(3,2)
y

tensor([[0.9844, 0.3532],
        [0.5512, 0.1864],
        [0.4622, 0.1076]])

In [ ]:
# reshape , view ,  stack
y.reshape(2,3)
y.view(2,3)
torch.stack((y,tensor1,tensor2),dim=1)

tensor([[[0.9844, 0.3532],
         [1.0000, 2.0000],
         [4.0000, 5.0000]],

        [[0.5512, 0.1864],
         [2.0000, 3.0000],
         [5.0000, 6.0000]],

        [[0.4622, 0.1076],
         [3.0000, 4.0000],
         [6.0000, 7.0000]]])

In [ ]:
# squeeze -1 dim and unsqueeze +1 dim

a = torch.rand(5,5)
a

tensor([[0.6669, 0.3906, 0.0990, 0.2494, 0.1330],
        [0.2757, 0.8015, 0.6529, 0.0118, 0.5495],
        [0.7720, 0.4918, 0.0263, 0.9243, 0.0577],
        [0.6494, 0.3867, 0.1929, 0.3182, 0.8222],
        [0.9819, 0.1364, 0.3815, 0.4132, 0.9775]])

In [ ]:
a.unsqueeze(dim=0).shape

torch.Size([1, 5, 5])

In [ ]:
# view and reshape only changes the shape of tensor
# but not the order of the data
# for eg

import torch

x = torch.tensor([[1, 2, 3], [4, 5, 6]])

y_view = x.view(3, 2)
print(y_view)  # Output: tensor([[1, 2], [3, 4], [5, 6]])

y_reshape = x.reshape(3, 2)
print(y_reshape)  # Output: tensor([[1, 2], [3, 4], [5, 6]])


# ** note ** - view share the same memory soo
# does not add additional memory where as
# reshape add addional memory though they both work almost same

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
# but permute changes the order of data too
# ** note - permute share same memory like here x and y_permute doing
# for eg:-

import torch

x = torch.tensor([[1, 2, 3], [4, 5, 6]])

y_permute = x.permute(1, 0)
print(y_permute)  # Output: tensor([[1, 4], [2, 5], [3, 6]])


tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
w = torch.arange(1,10).reshape(1,3,3)


In [ ]:
w[0,2,2]

tensor(9)

In [ ]:
# numpy array to tensor
array = np.arange(1.,10.)
array_convert = torch.from_numpy(array).type(torch.float32) # by defaut numpy  datatype is float64
tensor_a = torch.arange(1.,10.)  # by default torch datatype is float32
x = torch.add(array_convert , tensor_a) # so you might get dtype error so covert
x

tensor([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [ ]:
# torch to numpy
tensor_b = tensor_a.numpy()
tensor_b , tensor_a

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
random_seed = 42
torch.manual_seed(random_seed)
x=torch.rand(2,3)
torch.manual_seed(random_seed)
y=torch.rand(2,3)
torch.manual_seed(random_seed)
z=torch.rand(2,3)
print(x==y)

np.random.seed(random_seed)
a = np.random.rand(2,3)
np.random.seed(random_seed)
b = np.random.rand(2,3)
print(a==b)

tensor([[True, True, True],
        [True, True, True]])
[[ True  True  True]
 [ True  True  True]]


# **Reproducibility**

this reproduce the same output again and again and we use this in random tensor to minimize the randomness.
this is important because:


1.   in debuging and testing while testing everytime we run it give random number output and this makes difficult to test so we use this by seed
2.   model comparision





In [ ]:
tensor = torch.tensor([1.,2.,3.])
print(tensor , tensor.device)

tensor([1., 2., 3.]) cpu


In [ ]:
# moving tensor or models to gpu ( if available )
device = "cuda" if torch.cuda.is_available() else "cpu"
a_on_gpu = tensor.to(device)
print(a_on_gpu.device)
# lol, i dont have gpu :(haha)

cpu


**numpy doesnot work on gpu so if our tensor is in gpu device then we cant directly covert to numpy like TENSOR_ON_GPU.numpy() so we first have to move to cpu device then proceed further**

In [ ]:
a_back_on_cpu = a_on_gpu.cpu().type(torch.float64)
a = a_back_on_cpu.numpy()
ab = np.arange(1.,10.)
print(ab.dtype , a.dtype)

float64 float64


# **exercises**

In [ ]:
tensor_a = torch.rand(size=(7,7))
print(tensor_a)

tensor([[0.2566, 0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694],
        [0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832],
        [0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343],
        [0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895],
        [0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103, 0.6440]])


In [ ]:
tensor_b = torch.rand(1,7)
tensor_c = torch.mm(tensor_a,tensor_b.T)
print(tensor_c)

tensor([[2.2464],
        [1.9512],
        [1.0678],
        [1.0574],
        [1.9265],
        [1.9388],
        [1.1038]])


In [ ]:
seed = 0
torch.manual_seed(seed)
tensor_c = torch.mm(tensor_a,tensor_b.T)
print(tensor_c)

tensor([[2.2464],
        [1.9512],
        [1.0678],
        [1.0574],
        [1.9265],
        [1.9388],
        [1.1038]])


In [ ]:
seed_a = 1234
torch.cuda.manual_seed(seed_a)